### PR TITLE
Votes

### LINKED ISSUE #10: Compilation Error literal strings comparison
`assert(electionGetTribeName(sample, 12) != "ALL UPPER CASE");`
```Bash
error: comparison with string literal results in unspecified behavior [-Werror=address]
     assert(electionGetTribeName(sample, 12) != "ALL UPPER CASE");
                                             ^
```

### PR DESCRIPTION
**Pull request by danibondar**
added tests for add/remove votes and for remove tribe

### CODE REVIEW

File: election_tests.c [hunk 1]
```diff
@@ -202,8 +202,18 @@ bool subAddTribeExtremeIdValues(Election sample) {
     ASSERT_TEST(electionGetTribeName(sample, INT_MIN) == NULL);
     return true;
 }
-
+bool subAddTribeOrderOfReturn(Election sample) {
```
Comment (gur111) [inline election_tests.c]: Rename to `subAddTribeErrorPrecendence`

File: election_tests.c [hunk 2]
```diff
@@ -21,8 +20,10 @@
 // Also, good luck. You'll need it
 #endif
 
-#ifdef __unix__
-#define WITH_FORK
+#include "../election/augmented_map.h"
+
+#ifdef __MACH__
+//#define WITH_FORK
```
Comment (gur111) [inline election_tests.c]: Uncomment

File: election_tests.c [hunk 3]
```diff
@@ -21,8 +20,10 @@
 // Also, good luck. You'll need it
 #endif
 
-#ifdef __unix__
-#define WITH_FORK
+#include "../election/augmented_map.h"
```
Comment (gur111) [inline election_tests.c]: Remove

File: election_tests.c [hunk 4]
```diff
@@ -126,24 +129,33 @@ bool subAddTribeExist(Election sample) {
...
+    free(tribe_name);
+
     // Make sure names match
-    ASSERT_TEST(strcmp(electionGetTribeName(sample, 1),
-                       electionGetTribeName(sample, 11)) == 0);
-    // Make sure the names are different instances
-    ASSERT_TEST(electionGetTribeName(sample, 1) !=
-                electionGetTribeName(sample, 11));
+    tribe_name = electionGetTribeName(sample, 1);
+    char *tribe_name_2 = electionGetTribeName(sample, 11);
```
Comment (gur111) [inline election_tests.c]: No nee for underscore before the 2. Simply `tribe_name2`

File: election_tests.c [hunk 5]
```diff
@@ -178,38 +190,107 @@ bool subAddTribeValidName(Election sample) {
...
+    char *tribe_name = electionGetTribeName(sample, 11);
+    ASSERT_TEST(strcmp(tribe_name, "re added") == 0);
     ASSERT_TEST(electionRemoveTribe(sample, 11) == ELECTION_SUCCESS);
     ASSERT_TEST(electionAddTribe(sample, 11, "and again") == ELECTION_SUCCESS);
+    free(tribe_name);
+    return true;
+}
+
+bool subRemoveTribeNullArgument(Election sample) {
+    assert(electionRemoveTribe(NULL, 1) == ELECTION_NULL_ARGUMENT);
```
Comment (gur111) [inline election_tests.c]: Replace `assert` with `ASSER_TEST`

Comment (gur111) [reply election_tests.c]: I same for all the rest of those

File: election_tests.c [hunk 6]
```diff
@@ -366,9 +465,191 @@ bool subStressAddThenRemove(Election sample) {
         ASSERT_TEST(electionRemoveTribe(sample, i + 100) == ELECTION_SUCCESS);
         // TODO: Add some votes
     }
-
     return status;
 }
+
+bool subAddVotesInvalidId(Election sample) {
+    assert(electionAddVote(sample, -1, 11, 2) == ELECTION_INVALID_ID);
```
Comment (gur111) [inline election_tests.c]: ASSERTS!!!!

File: election_tests.c [hunk 7]
```diff
@@ -366,9 +465,191 @@ bool subStressAddThenRemove(Election sample) {
...
+    assert(electionSetTribeName(sample, 11, "fine name") == ELECTION_SUCCESS);
+    return true;
+}
+/**
+ * sub tests for Getting tribe names.
+ */
+bool subGetTribeNameNullArgument(Election sample) {
+    char *tribe_name = electionGetTribeName(NULL, 11);
+    assert(tribe_name == NULL);
+    free(tribe_name);
```
Comment (gur111) [inline election_tests.c]: useless.

File: election_tests.c [hunk 8]
```diff
@@ -366,9 +465,191 @@ bool subStressAddThenRemove(Election sample) {
...
+
+bool subGetTribeNameComperingStrings(Election sample) {
+    char *tribe_name = electionGetTribeName(sample, 11);
+    assert(strcmp(tribe_name, "tribe a") == 0);
+    assert(electionRemoveTribe(sample, 11) == ELECTION_SUCCESS);
+    free(tribe_name);
+
+    tribe_name = electionGetTribeName(sample, 11);
+    assert(tribe_name == NULL);
+    free(tribe_name);
```
Comment (gur111) [inline election_tests.c]: Useless

File: election_tests.c [hunk 9]
```diff
@@ -366,9 +465,191 @@ bool subStressAddThenRemove(Election sample) {
...
+        assert(key == NULL);
+    }
+    AUG_MAP_FOREACH(key,sample.areas){
+        assert(key == NULL);
+    }
+    AUG_MAP_FOREACH(key,sample.votes_by_area){
+        assert(key == NULL);
+    }*/
+    return true;
+}
```
Comment (gur111) [inline election_tests.c:668]: What's null map?

File: election_tests.c [hunk 10]
```diff
@@ -377,7 +658,11 @@ bool subStressAddThenRemove(Election sample) {
  * possible.
  */
 
-void testCreate() {}
+void testCreate() {
+    printf("Testing %s tests:\n", "'Create Map'");
+    TEST_WITH_SAMPLE(subtestCreateNullMap, "checkin if new election is empty");
```
Comment (gur111) [inline election_tests.c]: typo

File: election_tests.c [hunk 11]
```diff
@@ -406,24 +701,55 @@ void testAddArea() {
...
-    TEST_WITH_SAMPLE(subRemoveAreaReadd, "Re-Adding Area");
+    TEST_WITH_SAMPLE(subRemoveAreaReAdd, "Re-Adding Area");
 }
+
 void testRemoveAreas() {}
-void testAddVote() {}
-void testRemoveVote() {}
+
+void testAddVote() {
+    TEST_WITH_SAMPLE(subAddVotesNullArgument, "Inserting Null argument");
```
Comment (gur111) [inline election_tests.c:733]: printf title

File: election_tests.c [hunk 12]
```diff
@@ -406,24 +701,55 @@ void testAddArea() {
...
+    TEST_WITH_SAMPLE(subRemoveVotesNonExisting,
+                     "Non Existing tribes and areas checking order of errors");
+}
+
 void testComputeAreasToTribesMapping() {}
-void testSetTribeName() {}
-void testGetTribeName() {}
+
+void testSetTribeName() {
+    TEST_WITH_SAMPLE(subSetTribeNameDifferentStrings,
```
Comment (gur111) [inline election_tests.c:750]: printf title

File: election_tests.c [hunk 13]
```diff
@@ -406,24 +701,55 @@ void testAddArea() {
...
+                     "trying to insert different strings");
+    TEST_WITH_SAMPLE(subSetTribeNameInvalidId, "inserting invalid id`s");
+    TEST_WITH_SAMPLE(subSetTribeNameNULLArgument, "inserting null arguments");
+    TEST_WITH_SAMPLE(sudSetTribeNameTribeNotExits,
+                     "trying to set name for not existing tribe");
+    TEST_WITH_SAMPLE(subSetTribeNameErrorPrecedence, "checking order of errors");
+}
+
+void testGetTribeName() {
+    TEST_WITH_SAMPLE(subGetTribeNameNullArgument, "inserting null arguments");
```
Comment (gur111) [inline election_tests.c]: printf title

**Review by gur111 — CHANGES_REQUESTED** [review]

**Review by gur111 — APPROVED** [review]
